/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TvRouteImport } from './routes/tv'
import { Route as RevistaRouteImport } from './routes/revista'
import { Route as RedactoresRouteImport } from './routes/redactores'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as PremiosMvpRouteImport } from './routes/premios-mvp'
import { Route as PatrocinadoresRouteImport } from './routes/patrocinadores'
import { Route as PaisesRouteImport } from './routes/paises'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as AvisoLegalRouteImport } from './routes/aviso-legal'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResultadosIndexRouteImport } from './routes/resultados.index'
import { Route as NoticiasIndexRouteImport } from './routes/noticias.index'
import { Route as EventosIndexRouteImport } from './routes/eventos.index'
import { Route as EntrevistasIndexRouteImport } from './routes/entrevistas.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as CountryIndexRouteImport } from './routes/$country.index'
import { Route as SobreSlugRouteImport } from './routes/sobre.$slug'
import { Route as ResultadosEventoRouteImport } from './routes/resultados.$evento'
import { Route as PatinadoresSlugRouteImport } from './routes/patinadores.$slug'
import { Route as NoticiasSlugRouteImport } from './routes/noticias.$slug'
import { Route as LegalSlugRouteImport } from './routes/legal.$slug'
import { Route as HubCountryRouteImport } from './routes/hub.$country'
import { Route as EventsSlugRouteImport } from './routes/events.$slug'
import { Route as EventosSlugRouteImport } from './routes/eventos.$slug'
import { Route as EspanaRollerzoneTvRouteImport } from './routes/espana.rollerzone-tv'
import { Route as EspanaPatinadoresRouteImport } from './routes/espana.patinadores'
import { Route as EspanaMvpRouteImport } from './routes/espana.mvp'
import { Route as EspanaLiveRouteImport } from './routes/espana.live'
import { Route as EspanaFederacionesRouteImport } from './routes/espana.federaciones'
import { Route as EspanaClubesRouteImport } from './routes/espana.clubes'
import { Route as EntrevistasSlugRouteImport } from './routes/entrevistas.$slug'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as AdminTvHighlightsRouteImport } from './routes/admin.tv-highlights'
import { Route as AdminTvEmisionesRouteImport } from './routes/admin.tv-emisiones'
import { Route as AdminTvRouteImport } from './routes/admin.tv'
import { Route as AdminTickerRouteImport } from './routes/admin.ticker'
import { Route as AdminSobreNosotrosRouteImport } from './routes/admin.sobre-nosotros'
import { Route as AdminSectionsRouteImport } from './routes/admin.sections'
import { Route as AdminScheduleRouteImport } from './routes/admin.schedule'
import { Route as AdminRevistasRouteImport } from './routes/admin.revistas'
import { Route as AdminRevistaCtaRouteImport } from './routes/admin.revista-cta'
import { Route as AdminResultadosRouteImport } from './routes/admin.resultados'
import { Route as AdminRedactoresRouteImport } from './routes/admin.redactores'
import { Route as AdminPremiosMvpRouteImport } from './routes/admin.premios-mvp'
import { Route as AdminPendientesRouteImport } from './routes/admin.pendientes'
import { Route as AdminPatrocinadoresRouteImport } from './routes/admin.patrocinadores'
import { Route as AdminPatinadoresRouteImport } from './routes/admin.patinadores'
import { Route as AdminMedalleroRouteImport } from './routes/admin.medallero'
import { Route as AdminLiveResultsRouteImport } from './routes/admin.live-results'
import { Route as AdminLiveCenterRouteImport } from './routes/admin.live-center'
import { Route as AdminLegalRouteImport } from './routes/admin.legal'
import { Route as AdminHubLigaRouteImport } from './routes/admin.hub-liga'
import { Route as AdminFederacionesRouteImport } from './routes/admin.federaciones'
import { Route as AdminEventosRouteImport } from './routes/admin.eventos'
import { Route as AdminEquipoRouteImport } from './routes/admin.equipo'
import { Route as AdminEntrevistasRouteImport } from './routes/admin.entrevistas'
import { Route as AdminClubesRouteImport } from './routes/admin.clubes'
import { Route as AdminCategoriasRouteImport } from './routes/admin.categorias'
import { Route as AdminBannersRouteImport } from './routes/admin.banners'
import { Route as CountrySplatRouteImport } from './routes/$country.$'
import { Route as HubCountryIndexRouteImport } from './routes/hub.$country.index'
import { Route as NoticiasArticuloSlugRouteImport } from './routes/noticias.articulo.$slug'
import { Route as HubCountryTvRouteImport } from './routes/hub.$country.tv'
import { Route as HubCountryRfepRouteImport } from './routes/hub.$country.rfep'
import { Route as HubCountryPatinadoresRouteImport } from './routes/hub.$country.patinadores'
import { Route as HubCountryMvpRouteImport } from './routes/hub.$country.mvp'
import { Route as HubCountryLiveRouteImport } from './routes/hub.$country.live'
import { Route as HubCountryFederacionesRouteImport } from './routes/hub.$country.federaciones'
import { Route as HubCountryCompeticionRouteImport } from './routes/hub.$country.competicion'
import { Route as HubCountryClubesRouteImport } from './routes/hub.$country.clubes'
import { Route as HubCountrySectionRouteImport } from './routes/hub.$country.$section'
import { Route as ApiOgPremiosMvpDotsvgRouteImport } from './routes/api.og.premios-mvp[.]svg'
import { Route as HubCountryTvIndexRouteImport } from './routes/hub.$country.tv.index'
import { Route as HubCountryPatinadoresIndexRouteImport } from './routes/hub.$country.patinadores.index'
import { Route as HubCountryFederacionesIndexRouteImport } from './routes/hub.$country.federaciones.index'
import { Route as HubCountryCompeticionIndexRouteImport } from './routes/hub.$country.competicion.index'
import { Route as HubCountryClubesIndexRouteImport } from './routes/hub.$country.clubes.index'
import { Route as HubCountryTvSlugRouteImport } from './routes/hub.$country.tv.$slug'
import { Route as HubCountryRegionesCodeRouteImport } from './routes/hub.$country.regiones.$code'
import { Route as HubCountryPatinadoresSlugRouteImport } from './routes/hub.$country.patinadores.$slug'
import { Route as HubCountryFederacionesSlugRouteImport } from './routes/hub.$country.federaciones.$slug'
import { Route as HubCountryCompeticionLigaNacionalRouteImport } from './routes/hub.$country.competicion.liga-nacional'
import { Route as HubCountryClubesSlugRouteImport } from './routes/hub.$country.clubes.$slug'
import { Route as HubCountryCompeticionLigaNacionalIndexRouteImport } from './routes/hub.$country.competicion.liga-nacional.index'
import { Route as HubCountryCompeticionLigaNacionalResultadosRouteImport } from './routes/hub.$country.competicion.liga-nacional.resultados'
import { Route as HubCountryCompeticionLigaNacionalNoticiasRouteImport } from './routes/hub.$country.competicion.liga-nacional.noticias'
import { Route as HubCountryCompeticionLigaNacionalClasificacionesRouteImport } from './routes/hub.$country.competicion.liga-nacional.clasificaciones'
import { Route as HubCountryCompeticionLigaNacionalCalendarioRouteImport } from './routes/hub.$country.competicion.liga-nacional.calendario'

const TvRoute = TvRouteImport.update({
  id: '/tv',
  path: '/tv',
  getParentRoute: () => rootRouteImport,
} as any)
const RevistaRoute = RevistaRouteImport.update({
  id: '/revista',
  path: '/revista',
  getParentRoute: () => rootRouteImport,
} as any)
const RedactoresRoute = RedactoresRouteImport.update({
  id: '/redactores',
  path: '/redactores',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiosMvpRoute = PremiosMvpRouteImport.update({
  id: '/premios-mvp',
  path: '/premios-mvp',
  getParentRoute: () => rootRouteImport,
} as any)
const PatrocinadoresRoute = PatrocinadoresRouteImport.update({
  id: '/patrocinadores',
  path: '/patrocinadores',
  getParentRoute: () => rootRouteImport,
} as any)
const PaisesRoute = PaisesRouteImport.update({
  id: '/paises',
  path: '/paises',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisoLegalRoute = AvisoLegalRouteImport.update({
  id: '/aviso-legal',
  path: '/aviso-legal',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultadosIndexRoute = ResultadosIndexRouteImport.update({
  id: '/resultados/',
  path: '/resultados/',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasIndexRoute = NoticiasIndexRouteImport.update({
  id: '/noticias/',
  path: '/noticias/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosIndexRoute = EventosIndexRouteImport.update({
  id: '/eventos/',
  path: '/eventos/',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrevistasIndexRoute = EntrevistasIndexRouteImport.update({
  id: '/entrevistas/',
  path: '/entrevistas/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const CountryIndexRoute = CountryIndexRouteImport.update({
  id: '/$country/',
  path: '/$country/',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreSlugRoute = SobreSlugRouteImport.update({
  id: '/sobre/$slug',
  path: '/sobre/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultadosEventoRoute = ResultadosEventoRouteImport.update({
  id: '/resultados/$evento',
  path: '/resultados/$evento',
  getParentRoute: () => rootRouteImport,
} as any)
const PatinadoresSlugRoute = PatinadoresSlugRouteImport.update({
  id: '/patinadores/$slug',
  path: '/patinadores/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasSlugRoute = NoticiasSlugRouteImport.update({
  id: '/noticias/$slug',
  path: '/noticias/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalSlugRoute = LegalSlugRouteImport.update({
  id: '/legal/$slug',
  path: '/legal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const HubCountryRoute = HubCountryRouteImport.update({
  id: '/hub/$country',
  path: '/hub/$country',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosSlugRoute = EventosSlugRouteImport.update({
  id: '/eventos/$slug',
  path: '/eventos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EspanaRollerzoneTvRoute = EspanaRollerzoneTvRouteImport.update({
  id: '/espana/rollerzone-tv',
  path: '/espana/rollerzone-tv',
  getParentRoute: () => rootRouteImport,
} as any)
const EspanaPatinadoresRoute = EspanaPatinadoresRouteImport.update({
  id: '/espana/patinadores',
  path: '/espana/patinadores',
  getParentRoute: () => rootRouteImport,
} as any)
const EspanaMvpRoute = EspanaMvpRouteImport.update({
  id: '/espana/mvp',
  path: '/espana/mvp',
  getParentRoute: () => rootRouteImport,
} as any)
const EspanaLiveRoute = EspanaLiveRouteImport.update({
  id: '/espana/live',
  path: '/espana/live',
  getParentRoute: () => rootRouteImport,
} as any)
const EspanaFederacionesRoute = EspanaFederacionesRouteImport.update({
  id: '/espana/federaciones',
  path: '/espana/federaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const EspanaClubesRoute = EspanaClubesRouteImport.update({
  id: '/espana/clubes',
  path: '/espana/clubes',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrevistasSlugRoute = EntrevistasSlugRouteImport.update({
  id: '/entrevistas/$slug',
  path: '/entrevistas/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTvHighlightsRoute = AdminTvHighlightsRouteImport.update({
  id: '/tv-highlights',
  path: '/tv-highlights',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTvEmisionesRoute = AdminTvEmisionesRouteImport.update({
  id: '/tv-emisiones',
  path: '/tv-emisiones',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTvRoute = AdminTvRouteImport.update({
  id: '/tv',
  path: '/tv',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTickerRoute = AdminTickerRouteImport.update({
  id: '/ticker',
  path: '/ticker',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSobreNosotrosRoute = AdminSobreNosotrosRouteImport.update({
  id: '/sobre-nosotros',
  path: '/sobre-nosotros',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSectionsRoute = AdminSectionsRouteImport.update({
  id: '/sections',
  path: '/sections',
  getParentRoute: () => AdminRoute,
} as any)
const AdminScheduleRoute = AdminScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRevistasRoute = AdminRevistasRouteImport.update({
  id: '/revistas',
  path: '/revistas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRevistaCtaRoute = AdminRevistaCtaRouteImport.update({
  id: '/revista-cta',
  path: '/revista-cta',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResultadosRoute = AdminResultadosRouteImport.update({
  id: '/resultados',
  path: '/resultados',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRedactoresRoute = AdminRedactoresRouteImport.update({
  id: '/redactores',
  path: '/redactores',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPremiosMvpRoute = AdminPremiosMvpRouteImport.update({
  id: '/premios-mvp',
  path: '/premios-mvp',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPendientesRoute = AdminPendientesRouteImport.update({
  id: '/pendientes',
  path: '/pendientes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPatrocinadoresRoute = AdminPatrocinadoresRouteImport.update({
  id: '/patrocinadores',
  path: '/patrocinadores',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPatinadoresRoute = AdminPatinadoresRouteImport.update({
  id: '/patinadores',
  path: '/patinadores',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMedalleroRoute = AdminMedalleroRouteImport.update({
  id: '/medallero',
  path: '/medallero',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLiveResultsRoute = AdminLiveResultsRouteImport.update({
  id: '/live-results',
  path: '/live-results',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLiveCenterRoute = AdminLiveCenterRouteImport.update({
  id: '/live-center',
  path: '/live-center',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLegalRoute = AdminLegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHubLigaRoute = AdminHubLigaRouteImport.update({
  id: '/hub-liga',
  path: '/hub-liga',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFederacionesRoute = AdminFederacionesRouteImport.update({
  id: '/federaciones',
  path: '/federaciones',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventosRoute = AdminEventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEquipoRoute = AdminEquipoRouteImport.update({
  id: '/equipo',
  path: '/equipo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEntrevistasRoute = AdminEntrevistasRouteImport.update({
  id: '/entrevistas',
  path: '/entrevistas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClubesRoute = AdminClubesRouteImport.update({
  id: '/clubes',
  path: '/clubes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriasRoute = AdminCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBannersRoute = AdminBannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => AdminRoute,
} as any)
const CountrySplatRoute = CountrySplatRouteImport.update({
  id: '/$country/$',
  path: '/$country/$',
  getParentRoute: () => rootRouteImport,
} as any)
const HubCountryIndexRoute = HubCountryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HubCountryRoute,
} as any)
const NoticiasArticuloSlugRoute = NoticiasArticuloSlugRouteImport.update({
  id: '/noticias/articulo/$slug',
  path: '/noticias/articulo/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const HubCountryTvRoute = HubCountryTvRouteImport.update({
  id: '/tv',
  path: '/tv',
  getParentRoute: () => HubCountryRoute,
} as any)
const HubCountryRfepRoute = HubCountryRfepRouteImport.update({
  id: '/rfep',
  path: '/rfep',
  getParentRoute: () => HubCountryRoute,
} as any)
const HubCountryPatinadoresRoute = HubCountryPatinadoresRouteImport.update({
  id: '/patinadores',
  path: '/patinadores',
  getParentRoute: () => HubCountryRoute,
} as any)
const HubCountryMvpRoute = HubCountryMvpRouteImport.update({
  id: '/mvp',
  path: '/mvp',
  getParentRoute: () => HubCountryRoute,
} as any)
const HubCountryLiveRoute = HubCountryLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => HubCountryRoute,
} as any)
const HubCountryFederacionesRoute = HubCountryFederacionesRouteImport.update({
  id: '/federaciones',
  path: '/federaciones',
  getParentRoute: () => HubCountryRoute,
} as any)
const HubCountryCompeticionRoute = HubCountryCompeticionRouteImport.update({
  id: '/competicion',
  path: '/competicion',
  getParentRoute: () => HubCountryRoute,
} as any)
const HubCountryClubesRoute = HubCountryClubesRouteImport.update({
  id: '/clubes',
  path: '/clubes',
  getParentRoute: () => HubCountryRoute,
} as any)
const HubCountrySectionRoute = HubCountrySectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => HubCountryRoute,
} as any)
const ApiOgPremiosMvpDotsvgRoute = ApiOgPremiosMvpDotsvgRouteImport.update({
  id: '/api/og/premios-mvp.svg',
  path: '/api/og/premios-mvp.svg',
  getParentRoute: () => rootRouteImport,
} as any)
const HubCountryTvIndexRoute = HubCountryTvIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HubCountryTvRoute,
} as any)
const HubCountryPatinadoresIndexRoute =
  HubCountryPatinadoresIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => HubCountryPatinadoresRoute,
  } as any)
const HubCountryFederacionesIndexRoute =
  HubCountryFederacionesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => HubCountryFederacionesRoute,
  } as any)
const HubCountryCompeticionIndexRoute =
  HubCountryCompeticionIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => HubCountryCompeticionRoute,
  } as any)
const HubCountryClubesIndexRoute = HubCountryClubesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HubCountryClubesRoute,
} as any)
const HubCountryTvSlugRoute = HubCountryTvSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => HubCountryTvRoute,
} as any)
const HubCountryRegionesCodeRoute = HubCountryRegionesCodeRouteImport.update({
  id: '/regiones/$code',
  path: '/regiones/$code',
  getParentRoute: () => HubCountryRoute,
} as any)
const HubCountryPatinadoresSlugRoute =
  HubCountryPatinadoresSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => HubCountryPatinadoresRoute,
  } as any)
const HubCountryFederacionesSlugRoute =
  HubCountryFederacionesSlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => HubCountryFederacionesRoute,
  } as any)
const HubCountryCompeticionLigaNacionalRoute =
  HubCountryCompeticionLigaNacionalRouteImport.update({
    id: '/liga-nacional',
    path: '/liga-nacional',
    getParentRoute: () => HubCountryCompeticionRoute,
  } as any)
const HubCountryClubesSlugRoute = HubCountryClubesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => HubCountryClubesRoute,
} as any)
const HubCountryCompeticionLigaNacionalIndexRoute =
  HubCountryCompeticionLigaNacionalIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => HubCountryCompeticionLigaNacionalRoute,
  } as any)
const HubCountryCompeticionLigaNacionalResultadosRoute =
  HubCountryCompeticionLigaNacionalResultadosRouteImport.update({
    id: '/resultados',
    path: '/resultados',
    getParentRoute: () => HubCountryCompeticionLigaNacionalRoute,
  } as any)
const HubCountryCompeticionLigaNacionalNoticiasRoute =
  HubCountryCompeticionLigaNacionalNoticiasRouteImport.update({
    id: '/noticias',
    path: '/noticias',
    getParentRoute: () => HubCountryCompeticionLigaNacionalRoute,
  } as any)
const HubCountryCompeticionLigaNacionalClasificacionesRoute =
  HubCountryCompeticionLigaNacionalClasificacionesRouteImport.update({
    id: '/clasificaciones',
    path: '/clasificaciones',
    getParentRoute: () => HubCountryCompeticionLigaNacionalRoute,
  } as any)
const HubCountryCompeticionLigaNacionalCalendarioRoute =
  HubCountryCompeticionLigaNacionalCalendarioRouteImport.update({
    id: '/calendario',
    path: '/calendario',
    getParentRoute: () => HubCountryCompeticionLigaNacionalRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/paises': typeof PaisesRoute
  '/patrocinadores': typeof PatrocinadoresRoute
  '/premios-mvp': typeof PremiosMvpRoute
  '/privacidad': typeof PrivacidadRoute
  '/redactores': typeof RedactoresRoute
  '/revista': typeof RevistaRoute
  '/tv': typeof TvRoute
  '/$country/$': typeof CountrySplatRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/clubes': typeof AdminClubesRoute
  '/admin/entrevistas': typeof AdminEntrevistasRoute
  '/admin/equipo': typeof AdminEquipoRoute
  '/admin/eventos': typeof AdminEventosRoute
  '/admin/federaciones': typeof AdminFederacionesRoute
  '/admin/hub-liga': typeof AdminHubLigaRoute
  '/admin/legal': typeof AdminLegalRoute
  '/admin/live-center': typeof AdminLiveCenterRoute
  '/admin/live-results': typeof AdminLiveResultsRoute
  '/admin/medallero': typeof AdminMedalleroRoute
  '/admin/patinadores': typeof AdminPatinadoresRoute
  '/admin/patrocinadores': typeof AdminPatrocinadoresRoute
  '/admin/pendientes': typeof AdminPendientesRoute
  '/admin/premios-mvp': typeof AdminPremiosMvpRoute
  '/admin/redactores': typeof AdminRedactoresRoute
  '/admin/resultados': typeof AdminResultadosRoute
  '/admin/revista-cta': typeof AdminRevistaCtaRoute
  '/admin/revistas': typeof AdminRevistasRoute
  '/admin/schedule': typeof AdminScheduleRoute
  '/admin/sections': typeof AdminSectionsRoute
  '/admin/sobre-nosotros': typeof AdminSobreNosotrosRoute
  '/admin/ticker': typeof AdminTickerRoute
  '/admin/tv': typeof AdminTvRoute
  '/admin/tv-emisiones': typeof AdminTvEmisionesRoute
  '/admin/tv-highlights': typeof AdminTvHighlightsRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/entrevistas/$slug': typeof EntrevistasSlugRoute
  '/espana/clubes': typeof EspanaClubesRoute
  '/espana/federaciones': typeof EspanaFederacionesRoute
  '/espana/live': typeof EspanaLiveRoute
  '/espana/mvp': typeof EspanaMvpRoute
  '/espana/patinadores': typeof EspanaPatinadoresRoute
  '/espana/rollerzone-tv': typeof EspanaRollerzoneTvRoute
  '/eventos/$slug': typeof EventosSlugRoute
  '/events/$slug': typeof EventsSlugRoute
  '/hub/$country': typeof HubCountryRouteWithChildren
  '/legal/$slug': typeof LegalSlugRoute
  '/noticias/$slug': typeof NoticiasSlugRoute
  '/patinadores/$slug': typeof PatinadoresSlugRoute
  '/resultados/$evento': typeof ResultadosEventoRoute
  '/sobre/$slug': typeof SobreSlugRoute
  '/$country/': typeof CountryIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/entrevistas/': typeof EntrevistasIndexRoute
  '/eventos/': typeof EventosIndexRoute
  '/noticias/': typeof NoticiasIndexRoute
  '/resultados/': typeof ResultadosIndexRoute
  '/api/og/premios-mvp.svg': typeof ApiOgPremiosMvpDotsvgRoute
  '/hub/$country/$section': typeof HubCountrySectionRoute
  '/hub/$country/clubes': typeof HubCountryClubesRouteWithChildren
  '/hub/$country/competicion': typeof HubCountryCompeticionRouteWithChildren
  '/hub/$country/federaciones': typeof HubCountryFederacionesRouteWithChildren
  '/hub/$country/live': typeof HubCountryLiveRoute
  '/hub/$country/mvp': typeof HubCountryMvpRoute
  '/hub/$country/patinadores': typeof HubCountryPatinadoresRouteWithChildren
  '/hub/$country/rfep': typeof HubCountryRfepRoute
  '/hub/$country/tv': typeof HubCountryTvRouteWithChildren
  '/noticias/articulo/$slug': typeof NoticiasArticuloSlugRoute
  '/hub/$country/': typeof HubCountryIndexRoute
  '/hub/$country/clubes/$slug': typeof HubCountryClubesSlugRoute
  '/hub/$country/competicion/liga-nacional': typeof HubCountryCompeticionLigaNacionalRouteWithChildren
  '/hub/$country/federaciones/$slug': typeof HubCountryFederacionesSlugRoute
  '/hub/$country/patinadores/$slug': typeof HubCountryPatinadoresSlugRoute
  '/hub/$country/regiones/$code': typeof HubCountryRegionesCodeRoute
  '/hub/$country/tv/$slug': typeof HubCountryTvSlugRoute
  '/hub/$country/clubes/': typeof HubCountryClubesIndexRoute
  '/hub/$country/competicion/': typeof HubCountryCompeticionIndexRoute
  '/hub/$country/federaciones/': typeof HubCountryFederacionesIndexRoute
  '/hub/$country/patinadores/': typeof HubCountryPatinadoresIndexRoute
  '/hub/$country/tv/': typeof HubCountryTvIndexRoute
  '/hub/$country/competicion/liga-nacional/calendario': typeof HubCountryCompeticionLigaNacionalCalendarioRoute
  '/hub/$country/competicion/liga-nacional/clasificaciones': typeof HubCountryCompeticionLigaNacionalClasificacionesRoute
  '/hub/$country/competicion/liga-nacional/noticias': typeof HubCountryCompeticionLigaNacionalNoticiasRoute
  '/hub/$country/competicion/liga-nacional/resultados': typeof HubCountryCompeticionLigaNacionalResultadosRoute
  '/hub/$country/competicion/liga-nacional/': typeof HubCountryCompeticionLigaNacionalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/cookies': typeof CookiesRoute
  '/paises': typeof PaisesRoute
  '/patrocinadores': typeof PatrocinadoresRoute
  '/premios-mvp': typeof PremiosMvpRoute
  '/privacidad': typeof PrivacidadRoute
  '/redactores': typeof RedactoresRoute
  '/revista': typeof RevistaRoute
  '/tv': typeof TvRoute
  '/$country/$': typeof CountrySplatRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/clubes': typeof AdminClubesRoute
  '/admin/entrevistas': typeof AdminEntrevistasRoute
  '/admin/equipo': typeof AdminEquipoRoute
  '/admin/eventos': typeof AdminEventosRoute
  '/admin/federaciones': typeof AdminFederacionesRoute
  '/admin/hub-liga': typeof AdminHubLigaRoute
  '/admin/legal': typeof AdminLegalRoute
  '/admin/live-center': typeof AdminLiveCenterRoute
  '/admin/live-results': typeof AdminLiveResultsRoute
  '/admin/medallero': typeof AdminMedalleroRoute
  '/admin/patinadores': typeof AdminPatinadoresRoute
  '/admin/patrocinadores': typeof AdminPatrocinadoresRoute
  '/admin/pendientes': typeof AdminPendientesRoute
  '/admin/premios-mvp': typeof AdminPremiosMvpRoute
  '/admin/redactores': typeof AdminRedactoresRoute
  '/admin/resultados': typeof AdminResultadosRoute
  '/admin/revista-cta': typeof AdminRevistaCtaRoute
  '/admin/revistas': typeof AdminRevistasRoute
  '/admin/schedule': typeof AdminScheduleRoute
  '/admin/sections': typeof AdminSectionsRoute
  '/admin/sobre-nosotros': typeof AdminSobreNosotrosRoute
  '/admin/ticker': typeof AdminTickerRoute
  '/admin/tv': typeof AdminTvRoute
  '/admin/tv-emisiones': typeof AdminTvEmisionesRoute
  '/admin/tv-highlights': typeof AdminTvHighlightsRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/entrevistas/$slug': typeof EntrevistasSlugRoute
  '/espana/clubes': typeof EspanaClubesRoute
  '/espana/federaciones': typeof EspanaFederacionesRoute
  '/espana/live': typeof EspanaLiveRoute
  '/espana/mvp': typeof EspanaMvpRoute
  '/espana/patinadores': typeof EspanaPatinadoresRoute
  '/espana/rollerzone-tv': typeof EspanaRollerzoneTvRoute
  '/eventos/$slug': typeof EventosSlugRoute
  '/events/$slug': typeof EventsSlugRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/noticias/$slug': typeof NoticiasSlugRoute
  '/patinadores/$slug': typeof PatinadoresSlugRoute
  '/resultados/$evento': typeof ResultadosEventoRoute
  '/sobre/$slug': typeof SobreSlugRoute
  '/$country': typeof CountryIndexRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/entrevistas': typeof EntrevistasIndexRoute
  '/eventos': typeof EventosIndexRoute
  '/noticias': typeof NoticiasIndexRoute
  '/resultados': typeof ResultadosIndexRoute
  '/api/og/premios-mvp.svg': typeof ApiOgPremiosMvpDotsvgRoute
  '/hub/$country/$section': typeof HubCountrySectionRoute
  '/hub/$country/live': typeof HubCountryLiveRoute
  '/hub/$country/mvp': typeof HubCountryMvpRoute
  '/hub/$country/rfep': typeof HubCountryRfepRoute
  '/noticias/articulo/$slug': typeof NoticiasArticuloSlugRoute
  '/hub/$country': typeof HubCountryIndexRoute
  '/hub/$country/clubes/$slug': typeof HubCountryClubesSlugRoute
  '/hub/$country/federaciones/$slug': typeof HubCountryFederacionesSlugRoute
  '/hub/$country/patinadores/$slug': typeof HubCountryPatinadoresSlugRoute
  '/hub/$country/regiones/$code': typeof HubCountryRegionesCodeRoute
  '/hub/$country/tv/$slug': typeof HubCountryTvSlugRoute
  '/hub/$country/clubes': typeof HubCountryClubesIndexRoute
  '/hub/$country/competicion': typeof HubCountryCompeticionIndexRoute
  '/hub/$country/federaciones': typeof HubCountryFederacionesIndexRoute
  '/hub/$country/patinadores': typeof HubCountryPatinadoresIndexRoute
  '/hub/$country/tv': typeof HubCountryTvIndexRoute
  '/hub/$country/competicion/liga-nacional/calendario': typeof HubCountryCompeticionLigaNacionalCalendarioRoute
  '/hub/$country/competicion/liga-nacional/clasificaciones': typeof HubCountryCompeticionLigaNacionalClasificacionesRoute
  '/hub/$country/competicion/liga-nacional/noticias': typeof HubCountryCompeticionLigaNacionalNoticiasRoute
  '/hub/$country/competicion/liga-nacional/resultados': typeof HubCountryCompeticionLigaNacionalResultadosRoute
  '/hub/$country/competicion/liga-nacional': typeof HubCountryCompeticionLigaNacionalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/paises': typeof PaisesRoute
  '/patrocinadores': typeof PatrocinadoresRoute
  '/premios-mvp': typeof PremiosMvpRoute
  '/privacidad': typeof PrivacidadRoute
  '/redactores': typeof RedactoresRoute
  '/revista': typeof RevistaRoute
  '/tv': typeof TvRoute
  '/$country/$': typeof CountrySplatRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/clubes': typeof AdminClubesRoute
  '/admin/entrevistas': typeof AdminEntrevistasRoute
  '/admin/equipo': typeof AdminEquipoRoute
  '/admin/eventos': typeof AdminEventosRoute
  '/admin/federaciones': typeof AdminFederacionesRoute
  '/admin/hub-liga': typeof AdminHubLigaRoute
  '/admin/legal': typeof AdminLegalRoute
  '/admin/live-center': typeof AdminLiveCenterRoute
  '/admin/live-results': typeof AdminLiveResultsRoute
  '/admin/medallero': typeof AdminMedalleroRoute
  '/admin/patinadores': typeof AdminPatinadoresRoute
  '/admin/patrocinadores': typeof AdminPatrocinadoresRoute
  '/admin/pendientes': typeof AdminPendientesRoute
  '/admin/premios-mvp': typeof AdminPremiosMvpRoute
  '/admin/redactores': typeof AdminRedactoresRoute
  '/admin/resultados': typeof AdminResultadosRoute
  '/admin/revista-cta': typeof AdminRevistaCtaRoute
  '/admin/revistas': typeof AdminRevistasRoute
  '/admin/schedule': typeof AdminScheduleRoute
  '/admin/sections': typeof AdminSectionsRoute
  '/admin/sobre-nosotros': typeof AdminSobreNosotrosRoute
  '/admin/ticker': typeof AdminTickerRoute
  '/admin/tv': typeof AdminTvRoute
  '/admin/tv-emisiones': typeof AdminTvEmisionesRoute
  '/admin/tv-highlights': typeof AdminTvHighlightsRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/entrevistas/$slug': typeof EntrevistasSlugRoute
  '/espana/clubes': typeof EspanaClubesRoute
  '/espana/federaciones': typeof EspanaFederacionesRoute
  '/espana/live': typeof EspanaLiveRoute
  '/espana/mvp': typeof EspanaMvpRoute
  '/espana/patinadores': typeof EspanaPatinadoresRoute
  '/espana/rollerzone-tv': typeof EspanaRollerzoneTvRoute
  '/eventos/$slug': typeof EventosSlugRoute
  '/events/$slug': typeof EventsSlugRoute
  '/hub/$country': typeof HubCountryRouteWithChildren
  '/legal/$slug': typeof LegalSlugRoute
  '/noticias/$slug': typeof NoticiasSlugRoute
  '/patinadores/$slug': typeof PatinadoresSlugRoute
  '/resultados/$evento': typeof ResultadosEventoRoute
  '/sobre/$slug': typeof SobreSlugRoute
  '/$country/': typeof CountryIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/entrevistas/': typeof EntrevistasIndexRoute
  '/eventos/': typeof EventosIndexRoute
  '/noticias/': typeof NoticiasIndexRoute
  '/resultados/': typeof ResultadosIndexRoute
  '/api/og/premios-mvp.svg': typeof ApiOgPremiosMvpDotsvgRoute
  '/hub/$country/$section': typeof HubCountrySectionRoute
  '/hub/$country/clubes': typeof HubCountryClubesRouteWithChildren
  '/hub/$country/competicion': typeof HubCountryCompeticionRouteWithChildren
  '/hub/$country/federaciones': typeof HubCountryFederacionesRouteWithChildren
  '/hub/$country/live': typeof HubCountryLiveRoute
  '/hub/$country/mvp': typeof HubCountryMvpRoute
  '/hub/$country/patinadores': typeof HubCountryPatinadoresRouteWithChildren
  '/hub/$country/rfep': typeof HubCountryRfepRoute
  '/hub/$country/tv': typeof HubCountryTvRouteWithChildren
  '/noticias/articulo/$slug': typeof NoticiasArticuloSlugRoute
  '/hub/$country/': typeof HubCountryIndexRoute
  '/hub/$country/clubes/$slug': typeof HubCountryClubesSlugRoute
  '/hub/$country/competicion/liga-nacional': typeof HubCountryCompeticionLigaNacionalRouteWithChildren
  '/hub/$country/federaciones/$slug': typeof HubCountryFederacionesSlugRoute
  '/hub/$country/patinadores/$slug': typeof HubCountryPatinadoresSlugRoute
  '/hub/$country/regiones/$code': typeof HubCountryRegionesCodeRoute
  '/hub/$country/tv/$slug': typeof HubCountryTvSlugRoute
  '/hub/$country/clubes/': typeof HubCountryClubesIndexRoute
  '/hub/$country/competicion/': typeof HubCountryCompeticionIndexRoute
  '/hub/$country/federaciones/': typeof HubCountryFederacionesIndexRoute
  '/hub/$country/patinadores/': typeof HubCountryPatinadoresIndexRoute
  '/hub/$country/tv/': typeof HubCountryTvIndexRoute
  '/hub/$country/competicion/liga-nacional/calendario': typeof HubCountryCompeticionLigaNacionalCalendarioRoute
  '/hub/$country/competicion/liga-nacional/clasificaciones': typeof HubCountryCompeticionLigaNacionalClasificacionesRoute
  '/hub/$country/competicion/liga-nacional/noticias': typeof HubCountryCompeticionLigaNacionalNoticiasRoute
  '/hub/$country/competicion/liga-nacional/resultados': typeof HubCountryCompeticionLigaNacionalResultadosRoute
  '/hub/$country/competicion/liga-nacional/': typeof HubCountryCompeticionLigaNacionalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/aviso-legal'
    | '/cookies'
    | '/dashboard'
    | '/paises'
    | '/patrocinadores'
    | '/premios-mvp'
    | '/privacidad'
    | '/redactores'
    | '/revista'
    | '/tv'
    | '/$country/$'
    | '/admin/banners'
    | '/admin/categorias'
    | '/admin/clubes'
    | '/admin/entrevistas'
    | '/admin/equipo'
    | '/admin/eventos'
    | '/admin/federaciones'
    | '/admin/hub-liga'
    | '/admin/legal'
    | '/admin/live-center'
    | '/admin/live-results'
    | '/admin/medallero'
    | '/admin/patinadores'
    | '/admin/patrocinadores'
    | '/admin/pendientes'
    | '/admin/premios-mvp'
    | '/admin/redactores'
    | '/admin/resultados'
    | '/admin/revista-cta'
    | '/admin/revistas'
    | '/admin/schedule'
    | '/admin/sections'
    | '/admin/sobre-nosotros'
    | '/admin/ticker'
    | '/admin/tv'
    | '/admin/tv-emisiones'
    | '/admin/tv-highlights'
    | '/admin/usuarios'
    | '/entrevistas/$slug'
    | '/espana/clubes'
    | '/espana/federaciones'
    | '/espana/live'
    | '/espana/mvp'
    | '/espana/patinadores'
    | '/espana/rollerzone-tv'
    | '/eventos/$slug'
    | '/events/$slug'
    | '/hub/$country'
    | '/legal/$slug'
    | '/noticias/$slug'
    | '/patinadores/$slug'
    | '/resultados/$evento'
    | '/sobre/$slug'
    | '/$country/'
    | '/admin/'
    | '/dashboard/'
    | '/entrevistas/'
    | '/eventos/'
    | '/noticias/'
    | '/resultados/'
    | '/api/og/premios-mvp.svg'
    | '/hub/$country/$section'
    | '/hub/$country/clubes'
    | '/hub/$country/competicion'
    | '/hub/$country/federaciones'
    | '/hub/$country/live'
    | '/hub/$country/mvp'
    | '/hub/$country/patinadores'
    | '/hub/$country/rfep'
    | '/hub/$country/tv'
    | '/noticias/articulo/$slug'
    | '/hub/$country/'
    | '/hub/$country/clubes/$slug'
    | '/hub/$country/competicion/liga-nacional'
    | '/hub/$country/federaciones/$slug'
    | '/hub/$country/patinadores/$slug'
    | '/hub/$country/regiones/$code'
    | '/hub/$country/tv/$slug'
    | '/hub/$country/clubes/'
    | '/hub/$country/competicion/'
    | '/hub/$country/federaciones/'
    | '/hub/$country/patinadores/'
    | '/hub/$country/tv/'
    | '/hub/$country/competicion/liga-nacional/calendario'
    | '/hub/$country/competicion/liga-nacional/clasificaciones'
    | '/hub/$country/competicion/liga-nacional/noticias'
    | '/hub/$country/competicion/liga-nacional/resultados'
    | '/hub/$country/competicion/liga-nacional/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/aviso-legal'
    | '/cookies'
    | '/paises'
    | '/patrocinadores'
    | '/premios-mvp'
    | '/privacidad'
    | '/redactores'
    | '/revista'
    | '/tv'
    | '/$country/$'
    | '/admin/banners'
    | '/admin/categorias'
    | '/admin/clubes'
    | '/admin/entrevistas'
    | '/admin/equipo'
    | '/admin/eventos'
    | '/admin/federaciones'
    | '/admin/hub-liga'
    | '/admin/legal'
    | '/admin/live-center'
    | '/admin/live-results'
    | '/admin/medallero'
    | '/admin/patinadores'
    | '/admin/patrocinadores'
    | '/admin/pendientes'
    | '/admin/premios-mvp'
    | '/admin/redactores'
    | '/admin/resultados'
    | '/admin/revista-cta'
    | '/admin/revistas'
    | '/admin/schedule'
    | '/admin/sections'
    | '/admin/sobre-nosotros'
    | '/admin/ticker'
    | '/admin/tv'
    | '/admin/tv-emisiones'
    | '/admin/tv-highlights'
    | '/admin/usuarios'
    | '/entrevistas/$slug'
    | '/espana/clubes'
    | '/espana/federaciones'
    | '/espana/live'
    | '/espana/mvp'
    | '/espana/patinadores'
    | '/espana/rollerzone-tv'
    | '/eventos/$slug'
    | '/events/$slug'
    | '/legal/$slug'
    | '/noticias/$slug'
    | '/patinadores/$slug'
    | '/resultados/$evento'
    | '/sobre/$slug'
    | '/$country'
    | '/admin'
    | '/dashboard'
    | '/entrevistas'
    | '/eventos'
    | '/noticias'
    | '/resultados'
    | '/api/og/premios-mvp.svg'
    | '/hub/$country/$section'
    | '/hub/$country/live'
    | '/hub/$country/mvp'
    | '/hub/$country/rfep'
    | '/noticias/articulo/$slug'
    | '/hub/$country'
    | '/hub/$country/clubes/$slug'
    | '/hub/$country/federaciones/$slug'
    | '/hub/$country/patinadores/$slug'
    | '/hub/$country/regiones/$code'
    | '/hub/$country/tv/$slug'
    | '/hub/$country/clubes'
    | '/hub/$country/competicion'
    | '/hub/$country/federaciones'
    | '/hub/$country/patinadores'
    | '/hub/$country/tv'
    | '/hub/$country/competicion/liga-nacional/calendario'
    | '/hub/$country/competicion/liga-nacional/clasificaciones'
    | '/hub/$country/competicion/liga-nacional/noticias'
    | '/hub/$country/competicion/liga-nacional/resultados'
    | '/hub/$country/competicion/liga-nacional'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/aviso-legal'
    | '/cookies'
    | '/dashboard'
    | '/paises'
    | '/patrocinadores'
    | '/premios-mvp'
    | '/privacidad'
    | '/redactores'
    | '/revista'
    | '/tv'
    | '/$country/$'
    | '/admin/banners'
    | '/admin/categorias'
    | '/admin/clubes'
    | '/admin/entrevistas'
    | '/admin/equipo'
    | '/admin/eventos'
    | '/admin/federaciones'
    | '/admin/hub-liga'
    | '/admin/legal'
    | '/admin/live-center'
    | '/admin/live-results'
    | '/admin/medallero'
    | '/admin/patinadores'
    | '/admin/patrocinadores'
    | '/admin/pendientes'
    | '/admin/premios-mvp'
    | '/admin/redactores'
    | '/admin/resultados'
    | '/admin/revista-cta'
    | '/admin/revistas'
    | '/admin/schedule'
    | '/admin/sections'
    | '/admin/sobre-nosotros'
    | '/admin/ticker'
    | '/admin/tv'
    | '/admin/tv-emisiones'
    | '/admin/tv-highlights'
    | '/admin/usuarios'
    | '/entrevistas/$slug'
    | '/espana/clubes'
    | '/espana/federaciones'
    | '/espana/live'
    | '/espana/mvp'
    | '/espana/patinadores'
    | '/espana/rollerzone-tv'
    | '/eventos/$slug'
    | '/events/$slug'
    | '/hub/$country'
    | '/legal/$slug'
    | '/noticias/$slug'
    | '/patinadores/$slug'
    | '/resultados/$evento'
    | '/sobre/$slug'
    | '/$country/'
    | '/admin/'
    | '/dashboard/'
    | '/entrevistas/'
    | '/eventos/'
    | '/noticias/'
    | '/resultados/'
    | '/api/og/premios-mvp.svg'
    | '/hub/$country/$section'
    | '/hub/$country/clubes'
    | '/hub/$country/competicion'
    | '/hub/$country/federaciones'
    | '/hub/$country/live'
    | '/hub/$country/mvp'
    | '/hub/$country/patinadores'
    | '/hub/$country/rfep'
    | '/hub/$country/tv'
    | '/noticias/articulo/$slug'
    | '/hub/$country/'
    | '/hub/$country/clubes/$slug'
    | '/hub/$country/competicion/liga-nacional'
    | '/hub/$country/federaciones/$slug'
    | '/hub/$country/patinadores/$slug'
    | '/hub/$country/regiones/$code'
    | '/hub/$country/tv/$slug'
    | '/hub/$country/clubes/'
    | '/hub/$country/competicion/'
    | '/hub/$country/federaciones/'
    | '/hub/$country/patinadores/'
    | '/hub/$country/tv/'
    | '/hub/$country/competicion/liga-nacional/calendario'
    | '/hub/$country/competicion/liga-nacional/clasificaciones'
    | '/hub/$country/competicion/liga-nacional/noticias'
    | '/hub/$country/competicion/liga-nacional/resultados'
    | '/hub/$country/competicion/liga-nacional/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  AvisoLegalRoute: typeof AvisoLegalRoute
  CookiesRoute: typeof CookiesRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  PaisesRoute: typeof PaisesRoute
  PatrocinadoresRoute: typeof PatrocinadoresRoute
  PremiosMvpRoute: typeof PremiosMvpRoute
  PrivacidadRoute: typeof PrivacidadRoute
  RedactoresRoute: typeof RedactoresRoute
  RevistaRoute: typeof RevistaRoute
  TvRoute: typeof TvRoute
  CountrySplatRoute: typeof CountrySplatRoute
  EntrevistasSlugRoute: typeof EntrevistasSlugRoute
  EspanaClubesRoute: typeof EspanaClubesRoute
  EspanaFederacionesRoute: typeof EspanaFederacionesRoute
  EspanaLiveRoute: typeof EspanaLiveRoute
  EspanaMvpRoute: typeof EspanaMvpRoute
  EspanaPatinadoresRoute: typeof EspanaPatinadoresRoute
  EspanaRollerzoneTvRoute: typeof EspanaRollerzoneTvRoute
  EventosSlugRoute: typeof EventosSlugRoute
  EventsSlugRoute: typeof EventsSlugRoute
  HubCountryRoute: typeof HubCountryRouteWithChildren
  LegalSlugRoute: typeof LegalSlugRoute
  NoticiasSlugRoute: typeof NoticiasSlugRoute
  PatinadoresSlugRoute: typeof PatinadoresSlugRoute
  ResultadosEventoRoute: typeof ResultadosEventoRoute
  SobreSlugRoute: typeof SobreSlugRoute
  CountryIndexRoute: typeof CountryIndexRoute
  EntrevistasIndexRoute: typeof EntrevistasIndexRoute
  EventosIndexRoute: typeof EventosIndexRoute
  NoticiasIndexRoute: typeof NoticiasIndexRoute
  ResultadosIndexRoute: typeof ResultadosIndexRoute
  ApiOgPremiosMvpDotsvgRoute: typeof ApiOgPremiosMvpDotsvgRoute
  NoticiasArticuloSlugRoute: typeof NoticiasArticuloSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tv': {
      id: '/tv'
      path: '/tv'
      fullPath: '/tv'
      preLoaderRoute: typeof TvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revista': {
      id: '/revista'
      path: '/revista'
      fullPath: '/revista'
      preLoaderRoute: typeof RevistaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redactores': {
      id: '/redactores'
      path: '/redactores'
      fullPath: '/redactores'
      preLoaderRoute: typeof RedactoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premios-mvp': {
      id: '/premios-mvp'
      path: '/premios-mvp'
      fullPath: '/premios-mvp'
      preLoaderRoute: typeof PremiosMvpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patrocinadores': {
      id: '/patrocinadores'
      path: '/patrocinadores'
      fullPath: '/patrocinadores'
      preLoaderRoute: typeof PatrocinadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paises': {
      id: '/paises'
      path: '/paises'
      fullPath: '/paises'
      preLoaderRoute: typeof PaisesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aviso-legal': {
      id: '/aviso-legal'
      path: '/aviso-legal'
      fullPath: '/aviso-legal'
      preLoaderRoute: typeof AvisoLegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resultados/': {
      id: '/resultados/'
      path: '/resultados'
      fullPath: '/resultados/'
      preLoaderRoute: typeof ResultadosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias/': {
      id: '/noticias/'
      path: '/noticias'
      fullPath: '/noticias/'
      preLoaderRoute: typeof NoticiasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos/': {
      id: '/eventos/'
      path: '/eventos'
      fullPath: '/eventos/'
      preLoaderRoute: typeof EventosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrevistas/': {
      id: '/entrevistas/'
      path: '/entrevistas'
      fullPath: '/entrevistas/'
      preLoaderRoute: typeof EntrevistasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/$country/': {
      id: '/$country/'
      path: '/$country'
      fullPath: '/$country/'
      preLoaderRoute: typeof CountryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre/$slug': {
      id: '/sobre/$slug'
      path: '/sobre/$slug'
      fullPath: '/sobre/$slug'
      preLoaderRoute: typeof SobreSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resultados/$evento': {
      id: '/resultados/$evento'
      path: '/resultados/$evento'
      fullPath: '/resultados/$evento'
      preLoaderRoute: typeof ResultadosEventoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patinadores/$slug': {
      id: '/patinadores/$slug'
      path: '/patinadores/$slug'
      fullPath: '/patinadores/$slug'
      preLoaderRoute: typeof PatinadoresSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias/$slug': {
      id: '/noticias/$slug'
      path: '/noticias/$slug'
      fullPath: '/noticias/$slug'
      preLoaderRoute: typeof NoticiasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/$slug': {
      id: '/legal/$slug'
      path: '/legal/$slug'
      fullPath: '/legal/$slug'
      preLoaderRoute: typeof LegalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/$country': {
      id: '/hub/$country'
      path: '/hub/$country'
      fullPath: '/hub/$country'
      preLoaderRoute: typeof HubCountryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos/$slug': {
      id: '/eventos/$slug'
      path: '/eventos/$slug'
      fullPath: '/eventos/$slug'
      preLoaderRoute: typeof EventosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/espana/rollerzone-tv': {
      id: '/espana/rollerzone-tv'
      path: '/espana/rollerzone-tv'
      fullPath: '/espana/rollerzone-tv'
      preLoaderRoute: typeof EspanaRollerzoneTvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/espana/patinadores': {
      id: '/espana/patinadores'
      path: '/espana/patinadores'
      fullPath: '/espana/patinadores'
      preLoaderRoute: typeof EspanaPatinadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/espana/mvp': {
      id: '/espana/mvp'
      path: '/espana/mvp'
      fullPath: '/espana/mvp'
      preLoaderRoute: typeof EspanaMvpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/espana/live': {
      id: '/espana/live'
      path: '/espana/live'
      fullPath: '/espana/live'
      preLoaderRoute: typeof EspanaLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/espana/federaciones': {
      id: '/espana/federaciones'
      path: '/espana/federaciones'
      fullPath: '/espana/federaciones'
      preLoaderRoute: typeof EspanaFederacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/espana/clubes': {
      id: '/espana/clubes'
      path: '/espana/clubes'
      fullPath: '/espana/clubes'
      preLoaderRoute: typeof EspanaClubesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrevistas/$slug': {
      id: '/entrevistas/$slug'
      path: '/entrevistas/$slug'
      fullPath: '/entrevistas/$slug'
      preLoaderRoute: typeof EntrevistasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tv-highlights': {
      id: '/admin/tv-highlights'
      path: '/tv-highlights'
      fullPath: '/admin/tv-highlights'
      preLoaderRoute: typeof AdminTvHighlightsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tv-emisiones': {
      id: '/admin/tv-emisiones'
      path: '/tv-emisiones'
      fullPath: '/admin/tv-emisiones'
      preLoaderRoute: typeof AdminTvEmisionesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tv': {
      id: '/admin/tv'
      path: '/tv'
      fullPath: '/admin/tv'
      preLoaderRoute: typeof AdminTvRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ticker': {
      id: '/admin/ticker'
      path: '/ticker'
      fullPath: '/admin/ticker'
      preLoaderRoute: typeof AdminTickerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sobre-nosotros': {
      id: '/admin/sobre-nosotros'
      path: '/sobre-nosotros'
      fullPath: '/admin/sobre-nosotros'
      preLoaderRoute: typeof AdminSobreNosotrosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sections': {
      id: '/admin/sections'
      path: '/sections'
      fullPath: '/admin/sections'
      preLoaderRoute: typeof AdminSectionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/schedule': {
      id: '/admin/schedule'
      path: '/schedule'
      fullPath: '/admin/schedule'
      preLoaderRoute: typeof AdminScheduleRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/revistas': {
      id: '/admin/revistas'
      path: '/revistas'
      fullPath: '/admin/revistas'
      preLoaderRoute: typeof AdminRevistasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/revista-cta': {
      id: '/admin/revista-cta'
      path: '/revista-cta'
      fullPath: '/admin/revista-cta'
      preLoaderRoute: typeof AdminRevistaCtaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/resultados': {
      id: '/admin/resultados'
      path: '/resultados'
      fullPath: '/admin/resultados'
      preLoaderRoute: typeof AdminResultadosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/redactores': {
      id: '/admin/redactores'
      path: '/redactores'
      fullPath: '/admin/redactores'
      preLoaderRoute: typeof AdminRedactoresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/premios-mvp': {
      id: '/admin/premios-mvp'
      path: '/premios-mvp'
      fullPath: '/admin/premios-mvp'
      preLoaderRoute: typeof AdminPremiosMvpRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pendientes': {
      id: '/admin/pendientes'
      path: '/pendientes'
      fullPath: '/admin/pendientes'
      preLoaderRoute: typeof AdminPendientesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/patrocinadores': {
      id: '/admin/patrocinadores'
      path: '/patrocinadores'
      fullPath: '/admin/patrocinadores'
      preLoaderRoute: typeof AdminPatrocinadoresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/patinadores': {
      id: '/admin/patinadores'
      path: '/patinadores'
      fullPath: '/admin/patinadores'
      preLoaderRoute: typeof AdminPatinadoresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/medallero': {
      id: '/admin/medallero'
      path: '/medallero'
      fullPath: '/admin/medallero'
      preLoaderRoute: typeof AdminMedalleroRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/live-results': {
      id: '/admin/live-results'
      path: '/live-results'
      fullPath: '/admin/live-results'
      preLoaderRoute: typeof AdminLiveResultsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/live-center': {
      id: '/admin/live-center'
      path: '/live-center'
      fullPath: '/admin/live-center'
      preLoaderRoute: typeof AdminLiveCenterRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/legal': {
      id: '/admin/legal'
      path: '/legal'
      fullPath: '/admin/legal'
      preLoaderRoute: typeof AdminLegalRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/hub-liga': {
      id: '/admin/hub-liga'
      path: '/hub-liga'
      fullPath: '/admin/hub-liga'
      preLoaderRoute: typeof AdminHubLigaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/federaciones': {
      id: '/admin/federaciones'
      path: '/federaciones'
      fullPath: '/admin/federaciones'
      preLoaderRoute: typeof AdminFederacionesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/eventos': {
      id: '/admin/eventos'
      path: '/eventos'
      fullPath: '/admin/eventos'
      preLoaderRoute: typeof AdminEventosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/equipo': {
      id: '/admin/equipo'
      path: '/equipo'
      fullPath: '/admin/equipo'
      preLoaderRoute: typeof AdminEquipoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/entrevistas': {
      id: '/admin/entrevistas'
      path: '/entrevistas'
      fullPath: '/admin/entrevistas'
      preLoaderRoute: typeof AdminEntrevistasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clubes': {
      id: '/admin/clubes'
      path: '/clubes'
      fullPath: '/admin/clubes'
      preLoaderRoute: typeof AdminClubesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categorias': {
      id: '/admin/categorias'
      path: '/categorias'
      fullPath: '/admin/categorias'
      preLoaderRoute: typeof AdminCategoriasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/banners': {
      id: '/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AdminBannersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/$country/$': {
      id: '/$country/$'
      path: '/$country/$'
      fullPath: '/$country/$'
      preLoaderRoute: typeof CountrySplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/$country/': {
      id: '/hub/$country/'
      path: '/'
      fullPath: '/hub/$country/'
      preLoaderRoute: typeof HubCountryIndexRouteImport
      parentRoute: typeof HubCountryRoute
    }
    '/noticias/articulo/$slug': {
      id: '/noticias/articulo/$slug'
      path: '/noticias/articulo/$slug'
      fullPath: '/noticias/articulo/$slug'
      preLoaderRoute: typeof NoticiasArticuloSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/$country/tv': {
      id: '/hub/$country/tv'
      path: '/tv'
      fullPath: '/hub/$country/tv'
      preLoaderRoute: typeof HubCountryTvRouteImport
      parentRoute: typeof HubCountryRoute
    }
    '/hub/$country/rfep': {
      id: '/hub/$country/rfep'
      path: '/rfep'
      fullPath: '/hub/$country/rfep'
      preLoaderRoute: typeof HubCountryRfepRouteImport
      parentRoute: typeof HubCountryRoute
    }
    '/hub/$country/patinadores': {
      id: '/hub/$country/patinadores'
      path: '/patinadores'
      fullPath: '/hub/$country/patinadores'
      preLoaderRoute: typeof HubCountryPatinadoresRouteImport
      parentRoute: typeof HubCountryRoute
    }
    '/hub/$country/mvp': {
      id: '/hub/$country/mvp'
      path: '/mvp'
      fullPath: '/hub/$country/mvp'
      preLoaderRoute: typeof HubCountryMvpRouteImport
      parentRoute: typeof HubCountryRoute
    }
    '/hub/$country/live': {
      id: '/hub/$country/live'
      path: '/live'
      fullPath: '/hub/$country/live'
      preLoaderRoute: typeof HubCountryLiveRouteImport
      parentRoute: typeof HubCountryRoute
    }
    '/hub/$country/federaciones': {
      id: '/hub/$country/federaciones'
      path: '/federaciones'
      fullPath: '/hub/$country/federaciones'
      preLoaderRoute: typeof HubCountryFederacionesRouteImport
      parentRoute: typeof HubCountryRoute
    }
    '/hub/$country/competicion': {
      id: '/hub/$country/competicion'
      path: '/competicion'
      fullPath: '/hub/$country/competicion'
      preLoaderRoute: typeof HubCountryCompeticionRouteImport
      parentRoute: typeof HubCountryRoute
    }
    '/hub/$country/clubes': {
      id: '/hub/$country/clubes'
      path: '/clubes'
      fullPath: '/hub/$country/clubes'
      preLoaderRoute: typeof HubCountryClubesRouteImport
      parentRoute: typeof HubCountryRoute
    }
    '/hub/$country/$section': {
      id: '/hub/$country/$section'
      path: '/$section'
      fullPath: '/hub/$country/$section'
      preLoaderRoute: typeof HubCountrySectionRouteImport
      parentRoute: typeof HubCountryRoute
    }
    '/api/og/premios-mvp.svg': {
      id: '/api/og/premios-mvp.svg'
      path: '/api/og/premios-mvp.svg'
      fullPath: '/api/og/premios-mvp.svg'
      preLoaderRoute: typeof ApiOgPremiosMvpDotsvgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub/$country/tv/': {
      id: '/hub/$country/tv/'
      path: '/'
      fullPath: '/hub/$country/tv/'
      preLoaderRoute: typeof HubCountryTvIndexRouteImport
      parentRoute: typeof HubCountryTvRoute
    }
    '/hub/$country/patinadores/': {
      id: '/hub/$country/patinadores/'
      path: '/'
      fullPath: '/hub/$country/patinadores/'
      preLoaderRoute: typeof HubCountryPatinadoresIndexRouteImport
      parentRoute: typeof HubCountryPatinadoresRoute
    }
    '/hub/$country/federaciones/': {
      id: '/hub/$country/federaciones/'
      path: '/'
      fullPath: '/hub/$country/federaciones/'
      preLoaderRoute: typeof HubCountryFederacionesIndexRouteImport
      parentRoute: typeof HubCountryFederacionesRoute
    }
    '/hub/$country/competicion/': {
      id: '/hub/$country/competicion/'
      path: '/'
      fullPath: '/hub/$country/competicion/'
      preLoaderRoute: typeof HubCountryCompeticionIndexRouteImport
      parentRoute: typeof HubCountryCompeticionRoute
    }
    '/hub/$country/clubes/': {
      id: '/hub/$country/clubes/'
      path: '/'
      fullPath: '/hub/$country/clubes/'
      preLoaderRoute: typeof HubCountryClubesIndexRouteImport
      parentRoute: typeof HubCountryClubesRoute
    }
    '/hub/$country/tv/$slug': {
      id: '/hub/$country/tv/$slug'
      path: '/$slug'
      fullPath: '/hub/$country/tv/$slug'
      preLoaderRoute: typeof HubCountryTvSlugRouteImport
      parentRoute: typeof HubCountryTvRoute
    }
    '/hub/$country/regiones/$code': {
      id: '/hub/$country/regiones/$code'
      path: '/regiones/$code'
      fullPath: '/hub/$country/regiones/$code'
      preLoaderRoute: typeof HubCountryRegionesCodeRouteImport
      parentRoute: typeof HubCountryRoute
    }
    '/hub/$country/patinadores/$slug': {
      id: '/hub/$country/patinadores/$slug'
      path: '/$slug'
      fullPath: '/hub/$country/patinadores/$slug'
      preLoaderRoute: typeof HubCountryPatinadoresSlugRouteImport
      parentRoute: typeof HubCountryPatinadoresRoute
    }
    '/hub/$country/federaciones/$slug': {
      id: '/hub/$country/federaciones/$slug'
      path: '/$slug'
      fullPath: '/hub/$country/federaciones/$slug'
      preLoaderRoute: typeof HubCountryFederacionesSlugRouteImport
      parentRoute: typeof HubCountryFederacionesRoute
    }
    '/hub/$country/competicion/liga-nacional': {
      id: '/hub/$country/competicion/liga-nacional'
      path: '/liga-nacional'
      fullPath: '/hub/$country/competicion/liga-nacional'
      preLoaderRoute: typeof HubCountryCompeticionLigaNacionalRouteImport
      parentRoute: typeof HubCountryCompeticionRoute
    }
    '/hub/$country/clubes/$slug': {
      id: '/hub/$country/clubes/$slug'
      path: '/$slug'
      fullPath: '/hub/$country/clubes/$slug'
      preLoaderRoute: typeof HubCountryClubesSlugRouteImport
      parentRoute: typeof HubCountryClubesRoute
    }
    '/hub/$country/competicion/liga-nacional/': {
      id: '/hub/$country/competicion/liga-nacional/'
      path: '/'
      fullPath: '/hub/$country/competicion/liga-nacional/'
      preLoaderRoute: typeof HubCountryCompeticionLigaNacionalIndexRouteImport
      parentRoute: typeof HubCountryCompeticionLigaNacionalRoute
    }
    '/hub/$country/competicion/liga-nacional/resultados': {
      id: '/hub/$country/competicion/liga-nacional/resultados'
      path: '/resultados'
      fullPath: '/hub/$country/competicion/liga-nacional/resultados'
      preLoaderRoute: typeof HubCountryCompeticionLigaNacionalResultadosRouteImport
      parentRoute: typeof HubCountryCompeticionLigaNacionalRoute
    }
    '/hub/$country/competicion/liga-nacional/noticias': {
      id: '/hub/$country/competicion/liga-nacional/noticias'
      path: '/noticias'
      fullPath: '/hub/$country/competicion/liga-nacional/noticias'
      preLoaderRoute: typeof HubCountryCompeticionLigaNacionalNoticiasRouteImport
      parentRoute: typeof HubCountryCompeticionLigaNacionalRoute
    }
    '/hub/$country/competicion/liga-nacional/clasificaciones': {
      id: '/hub/$country/competicion/liga-nacional/clasificaciones'
      path: '/clasificaciones'
      fullPath: '/hub/$country/competicion/liga-nacional/clasificaciones'
      preLoaderRoute: typeof HubCountryCompeticionLigaNacionalClasificacionesRouteImport
      parentRoute: typeof HubCountryCompeticionLigaNacionalRoute
    }
    '/hub/$country/competicion/liga-nacional/calendario': {
      id: '/hub/$country/competicion/liga-nacional/calendario'
      path: '/calendario'
      fullPath: '/hub/$country/competicion/liga-nacional/calendario'
      preLoaderRoute: typeof HubCountryCompeticionLigaNacionalCalendarioRouteImport
      parentRoute: typeof HubCountryCompeticionLigaNacionalRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBannersRoute: typeof AdminBannersRoute
  AdminCategoriasRoute: typeof AdminCategoriasRoute
  AdminClubesRoute: typeof AdminClubesRoute
  AdminEntrevistasRoute: typeof AdminEntrevistasRoute
  AdminEquipoRoute: typeof AdminEquipoRoute
  AdminEventosRoute: typeof AdminEventosRoute
  AdminFederacionesRoute: typeof AdminFederacionesRoute
  AdminHubLigaRoute: typeof AdminHubLigaRoute
  AdminLegalRoute: typeof AdminLegalRoute
  AdminLiveCenterRoute: typeof AdminLiveCenterRoute
  AdminLiveResultsRoute: typeof AdminLiveResultsRoute
  AdminMedalleroRoute: typeof AdminMedalleroRoute
  AdminPatinadoresRoute: typeof AdminPatinadoresRoute
  AdminPatrocinadoresRoute: typeof AdminPatrocinadoresRoute
  AdminPendientesRoute: typeof AdminPendientesRoute
  AdminPremiosMvpRoute: typeof AdminPremiosMvpRoute
  AdminRedactoresRoute: typeof AdminRedactoresRoute
  AdminResultadosRoute: typeof AdminResultadosRoute
  AdminRevistaCtaRoute: typeof AdminRevistaCtaRoute
  AdminRevistasRoute: typeof AdminRevistasRoute
  AdminScheduleRoute: typeof AdminScheduleRoute
  AdminSectionsRoute: typeof AdminSectionsRoute
  AdminSobreNosotrosRoute: typeof AdminSobreNosotrosRoute
  AdminTickerRoute: typeof AdminTickerRoute
  AdminTvRoute: typeof AdminTvRoute
  AdminTvEmisionesRoute: typeof AdminTvEmisionesRoute
  AdminTvHighlightsRoute: typeof AdminTvHighlightsRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBannersRoute: AdminBannersRoute,
  AdminCategoriasRoute: AdminCategoriasRoute,
  AdminClubesRoute: AdminClubesRoute,
  AdminEntrevistasRoute: AdminEntrevistasRoute,
  AdminEquipoRoute: AdminEquipoRoute,
  AdminEventosRoute: AdminEventosRoute,
  AdminFederacionesRoute: AdminFederacionesRoute,
  AdminHubLigaRoute: AdminHubLigaRoute,
  AdminLegalRoute: AdminLegalRoute,
  AdminLiveCenterRoute: AdminLiveCenterRoute,
  AdminLiveResultsRoute: AdminLiveResultsRoute,
  AdminMedalleroRoute: AdminMedalleroRoute,
  AdminPatinadoresRoute: AdminPatinadoresRoute,
  AdminPatrocinadoresRoute: AdminPatrocinadoresRoute,
  AdminPendientesRoute: AdminPendientesRoute,
  AdminPremiosMvpRoute: AdminPremiosMvpRoute,
  AdminRedactoresRoute: AdminRedactoresRoute,
  AdminResultadosRoute: AdminResultadosRoute,
  AdminRevistaCtaRoute: AdminRevistaCtaRoute,
  AdminRevistasRoute: AdminRevistasRoute,
  AdminScheduleRoute: AdminScheduleRoute,
  AdminSectionsRoute: AdminSectionsRoute,
  AdminSobreNosotrosRoute: AdminSobreNosotrosRoute,
  AdminTickerRoute: AdminTickerRoute,
  AdminTvRoute: AdminTvRoute,
  AdminTvEmisionesRoute: AdminTvEmisionesRoute,
  AdminTvHighlightsRoute: AdminTvHighlightsRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface HubCountryClubesRouteChildren {
  HubCountryClubesSlugRoute: typeof HubCountryClubesSlugRoute
  HubCountryClubesIndexRoute: typeof HubCountryClubesIndexRoute
}

const HubCountryClubesRouteChildren: HubCountryClubesRouteChildren = {
  HubCountryClubesSlugRoute: HubCountryClubesSlugRoute,
  HubCountryClubesIndexRoute: HubCountryClubesIndexRoute,
}

const HubCountryClubesRouteWithChildren =
  HubCountryClubesRoute._addFileChildren(HubCountryClubesRouteChildren)

interface HubCountryCompeticionLigaNacionalRouteChildren {
  HubCountryCompeticionLigaNacionalCalendarioRoute: typeof HubCountryCompeticionLigaNacionalCalendarioRoute
  HubCountryCompeticionLigaNacionalClasificacionesRoute: typeof HubCountryCompeticionLigaNacionalClasificacionesRoute
  HubCountryCompeticionLigaNacionalNoticiasRoute: typeof HubCountryCompeticionLigaNacionalNoticiasRoute
  HubCountryCompeticionLigaNacionalResultadosRoute: typeof HubCountryCompeticionLigaNacionalResultadosRoute
  HubCountryCompeticionLigaNacionalIndexRoute: typeof HubCountryCompeticionLigaNacionalIndexRoute
}

const HubCountryCompeticionLigaNacionalRouteChildren: HubCountryCompeticionLigaNacionalRouteChildren =
  {
    HubCountryCompeticionLigaNacionalCalendarioRoute:
      HubCountryCompeticionLigaNacionalCalendarioRoute,
    HubCountryCompeticionLigaNacionalClasificacionesRoute:
      HubCountryCompeticionLigaNacionalClasificacionesRoute,
    HubCountryCompeticionLigaNacionalNoticiasRoute:
      HubCountryCompeticionLigaNacionalNoticiasRoute,
    HubCountryCompeticionLigaNacionalResultadosRoute:
      HubCountryCompeticionLigaNacionalResultadosRoute,
    HubCountryCompeticionLigaNacionalIndexRoute:
      HubCountryCompeticionLigaNacionalIndexRoute,
  }

const HubCountryCompeticionLigaNacionalRouteWithChildren =
  HubCountryCompeticionLigaNacionalRoute._addFileChildren(
    HubCountryCompeticionLigaNacionalRouteChildren,
  )

interface HubCountryCompeticionRouteChildren {
  HubCountryCompeticionLigaNacionalRoute: typeof HubCountryCompeticionLigaNacionalRouteWithChildren
  HubCountryCompeticionIndexRoute: typeof HubCountryCompeticionIndexRoute
}

const HubCountryCompeticionRouteChildren: HubCountryCompeticionRouteChildren = {
  HubCountryCompeticionLigaNacionalRoute:
    HubCountryCompeticionLigaNacionalRouteWithChildren,
  HubCountryCompeticionIndexRoute: HubCountryCompeticionIndexRoute,
}

const HubCountryCompeticionRouteWithChildren =
  HubCountryCompeticionRoute._addFileChildren(
    HubCountryCompeticionRouteChildren,
  )

interface HubCountryFederacionesRouteChildren {
  HubCountryFederacionesSlugRoute: typeof HubCountryFederacionesSlugRoute
  HubCountryFederacionesIndexRoute: typeof HubCountryFederacionesIndexRoute
}

const HubCountryFederacionesRouteChildren: HubCountryFederacionesRouteChildren =
  {
    HubCountryFederacionesSlugRoute: HubCountryFederacionesSlugRoute,
    HubCountryFederacionesIndexRoute: HubCountryFederacionesIndexRoute,
  }

const HubCountryFederacionesRouteWithChildren =
  HubCountryFederacionesRoute._addFileChildren(
    HubCountryFederacionesRouteChildren,
  )

interface HubCountryPatinadoresRouteChildren {
  HubCountryPatinadoresSlugRoute: typeof HubCountryPatinadoresSlugRoute
  HubCountryPatinadoresIndexRoute: typeof HubCountryPatinadoresIndexRoute
}

const HubCountryPatinadoresRouteChildren: HubCountryPatinadoresRouteChildren = {
  HubCountryPatinadoresSlugRoute: HubCountryPatinadoresSlugRoute,
  HubCountryPatinadoresIndexRoute: HubCountryPatinadoresIndexRoute,
}

const HubCountryPatinadoresRouteWithChildren =
  HubCountryPatinadoresRoute._addFileChildren(
    HubCountryPatinadoresRouteChildren,
  )

interface HubCountryTvRouteChildren {
  HubCountryTvSlugRoute: typeof HubCountryTvSlugRoute
  HubCountryTvIndexRoute: typeof HubCountryTvIndexRoute
}

const HubCountryTvRouteChildren: HubCountryTvRouteChildren = {
  HubCountryTvSlugRoute: HubCountryTvSlugRoute,
  HubCountryTvIndexRoute: HubCountryTvIndexRoute,
}

const HubCountryTvRouteWithChildren = HubCountryTvRoute._addFileChildren(
  HubCountryTvRouteChildren,
)

interface HubCountryRouteChildren {
  HubCountrySectionRoute: typeof HubCountrySectionRoute
  HubCountryClubesRoute: typeof HubCountryClubesRouteWithChildren
  HubCountryCompeticionRoute: typeof HubCountryCompeticionRouteWithChildren
  HubCountryFederacionesRoute: typeof HubCountryFederacionesRouteWithChildren
  HubCountryLiveRoute: typeof HubCountryLiveRoute
  HubCountryMvpRoute: typeof HubCountryMvpRoute
  HubCountryPatinadoresRoute: typeof HubCountryPatinadoresRouteWithChildren
  HubCountryRfepRoute: typeof HubCountryRfepRoute
  HubCountryTvRoute: typeof HubCountryTvRouteWithChildren
  HubCountryIndexRoute: typeof HubCountryIndexRoute
  HubCountryRegionesCodeRoute: typeof HubCountryRegionesCodeRoute
}

const HubCountryRouteChildren: HubCountryRouteChildren = {
  HubCountrySectionRoute: HubCountrySectionRoute,
  HubCountryClubesRoute: HubCountryClubesRouteWithChildren,
  HubCountryCompeticionRoute: HubCountryCompeticionRouteWithChildren,
  HubCountryFederacionesRoute: HubCountryFederacionesRouteWithChildren,
  HubCountryLiveRoute: HubCountryLiveRoute,
  HubCountryMvpRoute: HubCountryMvpRoute,
  HubCountryPatinadoresRoute: HubCountryPatinadoresRouteWithChildren,
  HubCountryRfepRoute: HubCountryRfepRoute,
  HubCountryTvRoute: HubCountryTvRouteWithChildren,
  HubCountryIndexRoute: HubCountryIndexRoute,
  HubCountryRegionesCodeRoute: HubCountryRegionesCodeRoute,
}

const HubCountryRouteWithChildren = HubCountryRoute._addFileChildren(
  HubCountryRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  AvisoLegalRoute: AvisoLegalRoute,
  CookiesRoute: CookiesRoute,
  DashboardRoute: DashboardRouteWithChildren,
  PaisesRoute: PaisesRoute,
  PatrocinadoresRoute: PatrocinadoresRoute,
  PremiosMvpRoute: PremiosMvpRoute,
  PrivacidadRoute: PrivacidadRoute,
  RedactoresRoute: RedactoresRoute,
  RevistaRoute: RevistaRoute,
  TvRoute: TvRoute,
  CountrySplatRoute: CountrySplatRoute,
  EntrevistasSlugRoute: EntrevistasSlugRoute,
  EspanaClubesRoute: EspanaClubesRoute,
  EspanaFederacionesRoute: EspanaFederacionesRoute,
  EspanaLiveRoute: EspanaLiveRoute,
  EspanaMvpRoute: EspanaMvpRoute,
  EspanaPatinadoresRoute: EspanaPatinadoresRoute,
  EspanaRollerzoneTvRoute: EspanaRollerzoneTvRoute,
  EventosSlugRoute: EventosSlugRoute,
  EventsSlugRoute: EventsSlugRoute,
  HubCountryRoute: HubCountryRouteWithChildren,
  LegalSlugRoute: LegalSlugRoute,
  NoticiasSlugRoute: NoticiasSlugRoute,
  PatinadoresSlugRoute: PatinadoresSlugRoute,
  ResultadosEventoRoute: ResultadosEventoRoute,
  SobreSlugRoute: SobreSlugRoute,
  CountryIndexRoute: CountryIndexRoute,
  EntrevistasIndexRoute: EntrevistasIndexRoute,
  EventosIndexRoute: EventosIndexRoute,
  NoticiasIndexRoute: NoticiasIndexRoute,
  ResultadosIndexRoute: ResultadosIndexRoute,
  ApiOgPremiosMvpDotsvgRoute: ApiOgPremiosMvpDotsvgRoute,
  NoticiasArticuloSlugRoute: NoticiasArticuloSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
