/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RankingIndexRouteImport } from './routes/ranking.index'
import { Route as NoticiasIndexRouteImport } from './routes/noticias.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as RankingSlugRouteImport } from './routes/ranking.$slug'
import { Route as NoticiasSlugRouteImport } from './routes/noticias.$slug'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as AdminPatinadoresRouteImport } from './routes/admin.patinadores'
import { Route as AdminCompeticionesRouteImport } from './routes/admin.competiciones'
import { Route as AdminClubesRouteImport } from './routes/admin.clubes'
import { Route as AdminCategoriasRouteImport } from './routes/admin.categorias'
import { Route as NoticiasArticuloSlugRouteImport } from './routes/noticias.articulo.$slug'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingIndexRoute = RankingIndexRouteImport.update({
  id: '/ranking/',
  path: '/ranking/',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasIndexRoute = NoticiasIndexRouteImport.update({
  id: '/noticias/',
  path: '/noticias/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const RankingSlugRoute = RankingSlugRouteImport.update({
  id: '/ranking/$slug',
  path: '/ranking/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasSlugRoute = NoticiasSlugRouteImport.update({
  id: '/noticias/$slug',
  path: '/noticias/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPatinadoresRoute = AdminPatinadoresRouteImport.update({
  id: '/patinadores',
  path: '/patinadores',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCompeticionesRoute = AdminCompeticionesRouteImport.update({
  id: '/competiciones',
  path: '/competiciones',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClubesRoute = AdminClubesRouteImport.update({
  id: '/clubes',
  path: '/clubes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriasRoute = AdminCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AdminRoute,
} as any)
const NoticiasArticuloSlugRoute = NoticiasArticuloSlugRouteImport.update({
  id: '/noticias/articulo/$slug',
  path: '/noticias/articulo/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/clubes': typeof AdminClubesRoute
  '/admin/competiciones': typeof AdminCompeticionesRoute
  '/admin/patinadores': typeof AdminPatinadoresRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/noticias/$slug': typeof NoticiasSlugRoute
  '/ranking/$slug': typeof RankingSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/noticias/': typeof NoticiasIndexRoute
  '/ranking/': typeof RankingIndexRoute
  '/noticias/articulo/$slug': typeof NoticiasArticuloSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/clubes': typeof AdminClubesRoute
  '/admin/competiciones': typeof AdminCompeticionesRoute
  '/admin/patinadores': typeof AdminPatinadoresRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/noticias/$slug': typeof NoticiasSlugRoute
  '/ranking/$slug': typeof RankingSlugRoute
  '/admin': typeof AdminIndexRoute
  '/noticias': typeof NoticiasIndexRoute
  '/ranking': typeof RankingIndexRoute
  '/noticias/articulo/$slug': typeof NoticiasArticuloSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/clubes': typeof AdminClubesRoute
  '/admin/competiciones': typeof AdminCompeticionesRoute
  '/admin/patinadores': typeof AdminPatinadoresRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/noticias/$slug': typeof NoticiasSlugRoute
  '/ranking/$slug': typeof RankingSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/noticias/': typeof NoticiasIndexRoute
  '/ranking/': typeof RankingIndexRoute
  '/noticias/articulo/$slug': typeof NoticiasArticuloSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/admin/categorias'
    | '/admin/clubes'
    | '/admin/competiciones'
    | '/admin/patinadores'
    | '/admin/usuarios'
    | '/noticias/$slug'
    | '/ranking/$slug'
    | '/admin/'
    | '/noticias/'
    | '/ranking/'
    | '/noticias/articulo/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin/categorias'
    | '/admin/clubes'
    | '/admin/competiciones'
    | '/admin/patinadores'
    | '/admin/usuarios'
    | '/noticias/$slug'
    | '/ranking/$slug'
    | '/admin'
    | '/noticias'
    | '/ranking'
    | '/noticias/articulo/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/admin/categorias'
    | '/admin/clubes'
    | '/admin/competiciones'
    | '/admin/patinadores'
    | '/admin/usuarios'
    | '/noticias/$slug'
    | '/ranking/$slug'
    | '/admin/'
    | '/noticias/'
    | '/ranking/'
    | '/noticias/articulo/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  NoticiasSlugRoute: typeof NoticiasSlugRoute
  RankingSlugRoute: typeof RankingSlugRoute
  NoticiasIndexRoute: typeof NoticiasIndexRoute
  RankingIndexRoute: typeof RankingIndexRoute
  NoticiasArticuloSlugRoute: typeof NoticiasArticuloSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking/': {
      id: '/ranking/'
      path: '/ranking'
      fullPath: '/ranking/'
      preLoaderRoute: typeof RankingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias/': {
      id: '/noticias/'
      path: '/noticias'
      fullPath: '/noticias/'
      preLoaderRoute: typeof NoticiasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/ranking/$slug': {
      id: '/ranking/$slug'
      path: '/ranking/$slug'
      fullPath: '/ranking/$slug'
      preLoaderRoute: typeof RankingSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias/$slug': {
      id: '/noticias/$slug'
      path: '/noticias/$slug'
      fullPath: '/noticias/$slug'
      preLoaderRoute: typeof NoticiasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/patinadores': {
      id: '/admin/patinadores'
      path: '/patinadores'
      fullPath: '/admin/patinadores'
      preLoaderRoute: typeof AdminPatinadoresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/competiciones': {
      id: '/admin/competiciones'
      path: '/competiciones'
      fullPath: '/admin/competiciones'
      preLoaderRoute: typeof AdminCompeticionesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clubes': {
      id: '/admin/clubes'
      path: '/clubes'
      fullPath: '/admin/clubes'
      preLoaderRoute: typeof AdminClubesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categorias': {
      id: '/admin/categorias'
      path: '/categorias'
      fullPath: '/admin/categorias'
      preLoaderRoute: typeof AdminCategoriasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/noticias/articulo/$slug': {
      id: '/noticias/articulo/$slug'
      path: '/noticias/articulo/$slug'
      fullPath: '/noticias/articulo/$slug'
      preLoaderRoute: typeof NoticiasArticuloSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminCategoriasRoute: typeof AdminCategoriasRoute
  AdminClubesRoute: typeof AdminClubesRoute
  AdminCompeticionesRoute: typeof AdminCompeticionesRoute
  AdminPatinadoresRoute: typeof AdminPatinadoresRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCategoriasRoute: AdminCategoriasRoute,
  AdminClubesRoute: AdminClubesRoute,
  AdminCompeticionesRoute: AdminCompeticionesRoute,
  AdminPatinadoresRoute: AdminPatinadoresRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  NoticiasSlugRoute: NoticiasSlugRoute,
  RankingSlugRoute: RankingSlugRoute,
  NoticiasIndexRoute: NoticiasIndexRoute,
  RankingIndexRoute: RankingIndexRoute,
  NoticiasArticuloSlugRoute: NoticiasArticuloSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
